application: wector-io
version: 1
runtime: php55
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /distance
  script: distance_matrix.php

- url: /geocode
  script: geocode.php

- url: /jss
  script: custom_content_script.js

- url: /use
  script: use.html

- url: /.*
  script: main.html